INSERT INTO categories (category_id,name) VALUES
('VEG001', 'Vegetables'),
('FRU002', 'Fruits'),
('HER003', 'Herbs'),
('BEV004', 'Beverages'),
('FOO005', 'Food Products');


INSERT INTO products (product_id, name, product_description, price, image_url, category_id, is_deleted, seller_id) VALUES

-- Vegetables
(5987321, 'Organic Carrot', 'These vibrant, organic carrots are grown without synthetic pesticides, packed with vitamins A, C, and K. Perfect for snacking, salads, or adding to a variety of dishes. These carrots have a naturally sweet and earthy flavor that is sure to please any palate.', 2.50, 'https://www.pexels.com/photo/close-up-photo-of-orange-carrots-1627635/', 'VEG001', false, 101),
(95987322, 'Organic Potato', 'These organic potatoes are grown in rich, healthy soil, offering a creamy texture and earthy flavor. Perfect for baking, boiling, mashing, or making crispy fries. Rich in potassium and essential nutrients, these potatoes are a versatile addition to any meal.', 3.00, 'https://www.pexels.com/photo/potatoes-1442482/', 'VEG001', false, 102),
(95987323, 'Organic Spinach', 'Freshly picked organic spinach, ideal for salads, smoothies, or as a side dish. This dark leafy green is packed with iron, calcium, and antioxidants, offering a healthy boost to any meal. It has a mild, slightly earthy flavor that pairs well with other vegetables.', 1.80, 'https://www.pexels.com/photo/green-spinach-1640777/', 'VEG001', false, 103),
(95987324, 'Organic Tomato', 'Sweet, juicy organic tomatoes, perfect for salads, sauces, or fresh salsas. Rich in lycopene, vitamins, and antioxidants, these tomatoes have a deep red color and a refreshing taste. Grown with care, they are a healthy choice for any dish.', 2.00, 'https://www.pexels.com/photo/red-tomatoes-594590/', 'VEG001', false, 104),
(95987325, 'Organic Broccoli', 'Fresh organic broccoli, full of vitamins, fiber, and antioxidants. Its rich green florets are perfect for steaming, stir-fries, or adding to casseroles. Packed with nutrients, it is a superfood that promotes heart health and boosts the immune system.', 2.80, 'https://www.pexels.com/photo/green-broccoli-573285/', 'VEG001', false, 105),
(95987326, 'Organic Cucumber', 'Crisp and refreshing organic cucumbers, perfect for salads, sandwiches, or snacking. Low in calories and high in water content, cucumbers provide hydration and are an excellent source of vitamins K and C. Their cool, mild flavor makes them a favorite for any meal.', 1.50, 'https://www.pexels.com/photo/sliced-cucumber-952377/', 'VEG001', false, 101),
(95987327, 'Organic Lettuce', 'Fresh, organic lettuce with a delicate, crisp texture. Perfect for healthy salads, wraps, or sandwiches. Full of fiber, vitamins, and minerals, this lettuce is the ideal base for any green dish, offering a light and refreshing taste.', 2.20, 'https://www.pexels.com/photo/green-lettuce-161573/', 'VEG001', false, 102),
(95987328, 'Organic Kale', 'Organic kale, one of the most nutrient-dense vegetables available, is packed with vitamins A, C, and K. Great for salads, smoothies, or sautéed dishes, kale offers a hearty texture and earthy flavor, perfect for superfood meals.', 3.50, 'https://www.pexels.com/photo/green-kale-952377/', 'VEG001', false, 103),
(95987329, 'Organic Bell Pepper', 'Organic bell peppers, sweet, crunchy, and bursting with vibrant colors. Rich in vitamin C and antioxidants, they are perfect for salads, stir-fries, or as a snack. Their natural sweetness makes them a favorite in any dish.', 2.70, 'https://www.pexels.com/photo/red-and-green-bell-peppers-1660027/', 'VEG001', false, 104),
(95987330, 'Organic Zucchini', 'Fresh, organic zucchini with a mild flavor and tender texture. Great for stir-fries, grilling, or adding to baked dishes. Zucchini is a healthy, low-calorie vegetable that pairs well with a variety of dishes, providing a boost of vitamins and minerals.', 2.10, 'https://www.pexels.com/photo/green-zucchini-952377/', 'VEG001', false, 105),
(95987341, 'Organic Sweet Potato', 'Sweet, organic sweet potatoes, rich in vitamins A and C, ideal for roasting, baking, or mashing. These naturally sweet and earthy potatoes are a nutritious addition to any meal and make for a hearty side dish.', 3.50, 'https://www.pexels.com/photo/organic-sweet-potato-1472227/', 'VEG001', false, 101),
(95987342, 'Organic Red Onion', 'Fresh organic red onions, perfect for adding a mild, sweet flavor to salads, salsas, or cooked dishes. These onions are full of antioxidants and have a vibrant color that adds visual appeal to any dish.', 2.30, 'https://www.pexels.com/photo/red-onions-368306/', 'VEG001', false, 102),
(95987343, 'Organic Butternut Squash', 'Sweet and creamy organic butternut squash, perfect for roasting, soups, or casseroles. Rich in vitamins A and C, this vegetable has a smooth texture and natural sweetness that enhances any dish.', 4.00, 'https://www.pexels.com/photo/organic-butternut-squash-1525225/', 'VEG001', false, 103),
(95987356, 'Organic Cauliflower', 'Fresh organic cauliflower, perfect for steaming, roasting, or making cauliflower rice. This versatile vegetable is rich in antioxidants, fiber, and vitamins, and it adds a mild, nutty flavor to any dish.', 3.20, 'https://www.pexels.com/photo/cauliflower-1179201/', 'VEG001', false, 121),
(95987357, 'Organic Leeks', 'Organic leeks, with a mild onion flavor and tender texture. Perfect for soups, stews, or adding to salads, leeks are full of vitamins and minerals that support digestive health.', 2.80, 'https://www.pexels.com/photo/leeks-1179201/', 'VEG001', false, 122),
(95987358, 'Organic Beetroot', 'Rich, organic beetroot, perfect for roasting, pickling, or adding to salads. Beets are known for their vibrant color and earthy taste, and they are packed with antioxidants, fiber, and vitamins.', 2.90, 'https://www.pexels.com/photo/beetroot-1101640/', 'VEG001', false, 123),
(95987359, 'Organic Cabbage', 'Organic green cabbage, perfect for making coleslaw, stir-frying, or adding to soups. Full of vitamin C, this crunchy vegetable is a great addition to any healthy meal.', 1.50, 'https://www.pexels.com/photo/green-cabbage-1179201/', 'VEG001', false, 124),
(95987360, 'Organic Garlic', 'Fresh organic garlic, great for adding flavor and aroma to a variety of dishes. Known for its strong, pungent flavor and numerous health benefits, garlic is a must-have ingredient in any kitchen.', 2.50, 'https://www.pexels.com/photo/garlic-1179201/', 'VEG001', false, 125),


-- Fruits
(95987331, 'Organic Apple', 'Sweet, crisp organic apples, perfect for a healthy snack or baking. Rich in dietary fiber and vitamin C, these apples are a natural source of antioxidants that promote heart health. Their refreshing taste makes them a go-to fruit for any time of day.', 3.00, 'https://www.pexels.com/photo/red-apples-162806/', 'FRU002', false, 101),
(95987332, 'Organic Banana', 'Organic bananas, rich in potassium and energy-boosting nutrients, perfect for smoothies, cereals, or as a snack. They have a creamy texture and naturally sweet flavor, making them a great addition to any meal or treat.', 1.20, 'https://www.pexels.com/photo/yellow-bananas-162806/', 'FRU002', false, 102),
(95987333, 'Organic Mango', 'Sweet and juicy organic mangoes, perfect for smoothies, desserts, or snacking. Rich in vitamins A and C, mangoes provide a tropical flavor with every bite. These organic mangoes have a soft texture and vibrant color.', 2.50, 'https://www.pexels.com/photo/yellow-mangoes-162806/', 'FRU002', false, 103),
(95987334, 'Organic Pineapple', 'Fresh organic pineapples, perfect for tropical smoothies, desserts, or grilling. Rich in vitamin C and antioxidants, pineapples are known for their tangy sweetness and unique flavor that adds a tropical flair to any dish.', 4.00, 'https://www.pexels.com/photo/pineapple-fruit-162806/', 'FRU002', false, 104),
(95987335, 'Organic Orange', 'Organic oranges, bursting with vitamin C, perfect for juicing, snacking, or adding to salads. These oranges are naturally sweet, with a refreshing citrus flavor that is ideal for boosting your immune system and adding a burst of freshness to any dish.', 2.20, 'https://www.pexels.com/photo/orange-fruit-162806/', 'FRU002', false, 105),
(95987344, 'Organic Pear', 'Juicy, organic pears, perfect for snacking or adding to fruit salads. These pears are naturally sweet with a soft, buttery texture and are packed with fiber and vitamin C, making them a healthy and refreshing treat.', 2.50, 'https://www.pexels.com/photo/organic-pear-547443/', 'FRU002', false, 103),
(95987345, 'Organic Peach', 'Fresh, organic peaches, packed with vitamins and antioxidants. These peaches have a juicy, sweet flesh that is perfect for smoothies, fruit salads, or baking into delicious desserts. Enjoy the taste of summer with every bite.', 3.00, 'https://www.pexels.com/photo/organic-peach-2104116/', 'FRU002', false, 104),
(95987346, 'Organic Kiwi', 'Tangy and sweet organic kiwis, a great source of vitamin C and dietary fiber. These small, green fruits are perfect for snacking, adding to fruit salads, or making refreshing smoothies with a tropical twist.', 2.80, 'https://www.pexels.com/photo/kiwi-fruit-5183471/', 'FRU002', false, 105),
(95987361, 'Organic Plum', 'Organic plums, juicy and sweet, perfect for snacking or adding to fruit salads. These fruits are rich in antioxidants, fiber, and vitamins, offering numerous health benefits.', 3.00, 'https://www.pexels.com/photo/plums-1472227/', 'FRU002', false, 126),
(95987362, 'Organic Apricot', 'Sweet, organic apricots, perfect for snacking or making jams and sauces. Apricots are rich in vitamins A and C, and they have a soft, velvety texture with a hint of tartness.', 2.40, 'https://www.pexels.com/photo/apricot-1472227/', 'FRU002', false, 127),
(95987363, 'Organic Papaya', 'Fresh organic papaya, rich in enzymes and perfect for smoothies, salads, or desserts. Papayas have a sweet, tropical flavor that is loved by many and offer great digestive benefits.', 4.00, 'https://www.pexels.com/photo/papaya-1472227/', 'FRU002', false, 128),
(95987364, 'Organic Cherry', 'Organic cherries, sweet and juicy, perfect for snacking or adding to pies and desserts. These cherries are packed with antioxidants and vitamins that support heart health and reduce inflammation.', 4.20, 'https://www.pexels.com/photo/cherry-1472227/', 'FRU002', false, 129),
(95987365, 'Organic Watermelon', 'Organic watermelon, sweet and juicy, perfect for hot summer days. This hydrating fruit is full of vitamins, especially vitamin C, and is low in calories, making it a refreshing, guilt-free treat.', 3.50, 'https://www.pexels.com/photo/watermelon-1472227/', 'FRU002', false, 130),
-- Herbs
(95987336, 'Organic Basil', 'Fresh organic basil, perfect for garnishing or adding flavor to sauces, pizzas, or salads. Its aromatic, sweet flavor enhances Mediterranean dishes and adds a fragrant note to any recipe. Packed with antioxidants, basil also offers a host of health benefits.', 1.80, 'https://www.pexels.com/photo/green-basil-952377/', 'HER003', false, 101),
(95987337, 'Organic Mint', 'Organic mint, with its refreshing and cooling flavor, is perfect for teas, desserts, and garnishing. It has a natural soothing effect and adds a refreshing twist to any drink or dish, making it a versatile herb for your kitchen.', 1.50, 'https://www.pexels.com/photo/green-mint-952377/', 'HER003', false, 102),
(95987338, 'Organic Parsley', 'Organic parsley, a popular herb known for its fresh, vibrant flavor. Ideal for garnishing or adding to soups, salads, or sauces. Packed with vitamins A, C, and K, parsley also offers a variety of health benefits, including promoting digestion.', 1.20, 'https://www.pexels.com/photo/green-parsley-952377/', 'HER003', false, 103),
(95987339, 'Organic Rosemary', 'Fragrant organic rosemary, perfect for seasoning meats, potatoes, and soups. This herb has a bold, piney flavor that adds depth to your cooking. Rich in antioxidants, rosemary also has beneficial effects on memory and concentration.', 2.00, 'https://www.pexels.com/photo/green-rosemary-952377/', 'HER003', false, 104),
(95987340, 'Organic Thyme', 'Organic thyme, a versatile herb used in a variety of dishes from soups to roasts. With its earthy flavor and delicate leaves, thyme pairs well with meats, vegetables, and stews. Rich in antioxidants and vitamins, thyme also supports respiratory health.', 2.10, 'https://www.pexels.com/photo/green-thyme-952377/', 'HER003', false, 105),
(95987347, 'Organic Chives', 'Organic chives, perfect for garnishing dishes like baked potatoes, salads, or omelets. These delicate green herbs have a mild onion flavor and add a fresh, vibrant touch to any dish.', 1.60, 'https://www.pexels.com/photo/green-chives-952377/', 'HER003', false, 101),
(95987348, 'Organic Lavender', 'Organic lavender, known for its calming properties and fragrant aroma. Ideal for making herbal teas, adding to baked goods, or using in aromatherapy. Lavender’s floral scent is also great for creating relaxing atmospheres.', 3.50, 'https://www.pexels.com/photo/lavender-herb-952377/', 'HER003', false, 102),
(95987349, 'Organic Lemon Balm', 'Fresh, organic lemon balm with a refreshing lemon scent. Perfect for making calming teas, adding flavor to dishes, or using in homemade skincare products. Known for its soothing properties, lemon balm is a versatile herb.', 2.20, 'https://www.pexels.com/photo/lemon-balm-952377/', 'HER003', false, 103),
(95987366, 'Organic Tarragon', 'Fresh organic tarragon, perfect for adding a mild, anise-like flavor to your dishes. This herb is ideal for flavoring meats, soups, and sauces, and has antioxidant and anti-inflammatory properties.', 2.80, 'https://www.pexels.com/photo/tarragon-1179201/', 'HER003', false, 131),
(95987367, 'Organic Chamomile', 'Organic chamomile flowers, perfect for making calming herbal teas. Chamomile has soothing properties, making it great for relaxation and reducing stress before bedtime.', 3.00, 'https://www.pexels.com/photo/chamomile-1179201/', 'HER003', false, 132),
(95987368, 'Organic Oregano', 'Organic oregano, perfect for Mediterranean dishes, pizza, and pasta. This fragrant herb is packed with antioxidants and has anti-inflammatory properties that are beneficial for overall health.', 2.50, 'https://www.pexels.com/photo/oregano-1179201/', 'HER003', false, 133),
(95987369, 'Organic Dill', 'Organic dill, ideal for making pickles or adding to fish dishes. This herb has a fresh, tangy flavor and is rich in vitamins A and C, along with essential minerals that support digestion.', 2.10, 'https://www.pexels.com/photo/dill-1179201/', 'HER003', false, 134),
(95987370, 'Organic Sage', 'Organic sage, perfect for seasoning meats, stews, and stuffing. Known for its earthy flavor, sage also has antioxidant and anti-inflammatory properties that promote good digestion.', 2.20, 'https://www.pexels.com/photo/sage-1179201/', 'HER003', false, 135),
-- Beverages
(95987350, 'Organic Green Juice', 'Freshly pressed organic green juice made from kale, spinach, cucumber, and celery. Packed with vitamins, minerals, and antioxidants, this juice is perfect for detoxing, boosting energy, and supporting your immune system.', 4.50, 'https://www.pexels.com/photo/green-juice-1421261/', 'BEV004', false, 105),
(95987351, 'Organic Coconut Milk', 'Organic coconut milk, rich and creamy, perfect for smoothies, curries, or baking. This dairy-free milk alternative is packed with healthy fats and has a naturally sweet flavor, making it a great addition to many dishes.', 3.80, 'https://www.pexels.com/photo/coconut-milk-1421261/', 'BEV004', false, 101),
(95987352, 'Organic Lemon Tea', 'Organic lemon tea made with fresh lemon zest and a blend of herbs, perfect for a refreshing and healthy beverage. It’s known for its detoxifying properties and can be enjoyed hot or iced, providing a burst of citrus flavor.', 3.20, 'https://www.pexels.com/photo/lemon-tea-1421261/', 'BEV004', false, 103),
(95987371, 'Organic Matcha Tea', 'Organic matcha tea, made from powdered green tea leaves. Packed with antioxidants and providing a gentle energy boost, matcha is perfect for those looking for a healthy, flavorful drink to start their day.', 5.00, 'https://www.pexels.com/photo/matcha-tea-1421261/', 'BEV004', false, 136),
(95987372, 'Organic Green Tea', 'Organic green tea, rich in antioxidants and perfect for promoting healthy digestion and boosting metabolism. This refreshing drink is ideal for those looking for a healthy, calming beverage.', 4.00, 'https://www.pexels.com/photo/green-tea-1421261/', 'BEV004', false, 137),
(95987373, 'Organic Ginger Tea', 'Organic ginger tea, a spicy, invigorating beverage known for its ability to soothe nausea and promote healthy digestion. This tea is great for boosting immunity and warming up during cold days.', 3.80, 'https://www.pexels.com/photo/ginger-tea-1421261/', 'BEV004', false, 138),
(95987374, 'Organic Coconut Water', 'Refreshing organic coconut water, perfect for hydration. Naturally rich in electrolytes, this beverage is a healthy alternative to sugary drinks and provides a natural boost to your energy levels.', 2.50, 'https://www.pexels.com/photo/coconut-water-1421261/', 'BEV004', false, 139),
(95987375, 'Organic Cold Brew Coffee', 'Organic cold brew coffee, smooth and rich, perfect for a refreshing caffeine boost. This cold-brewed coffee has a less acidic taste and is perfect for coffee lovers who prefer a smoother, less bitter cup.', 4.50, 'https://www.pexels.com/photo/cold-brew-coffee-1421261/', 'BEV004', false, 140),

-- Food Products
(95987353, 'Organic Almond Flour', 'Finely ground organic almonds, perfect for gluten-free baking, breading, or making smoothies. Almond flour is rich in healthy fats, protein, and fiber, providing a nutritious and versatile ingredient for your kitchen.', 5.50, 'https://www.pexels.com/photo/almond-flour-7520645/', 'FOO005', false, 102),
(95987354, 'Organic Chickpea Flour', 'Organic chickpea flour, made from ground chickpeas, perfect for gluten-free baking, making pancakes, or adding to savory dishes. This flour is high in protein, fiber, and essential nutrients, making it a healthy choice for any recipe.', 4.30, 'https://www.pexels.com/photo/chickpea-flour-7520645/', 'FOO005', false, 102),
(95987355, 'Organic Spelt Flour', 'Organic spelt flour, an ancient grain flour that is perfect for baking breads, cookies, and other delicious treats. Spelt has a nutty, slightly sweet flavor and is a great source of fiber, protein, and essential minerals.', 4.00, 'https://www.pexels.com/photo/spelt-flour-7520645/', 'FOO005', false, 103),
(95987376, 'Organic Quinoa', 'Organic quinoa, a nutritious and protein-packed grain that makes an excellent substitute for rice. High in fiber and essential amino acids, quinoa is great for salads, bowls, and as a side dish.', 5.00, 'https://www.pexels.com/photo/quinoa-1421261/', 'FOO005', false, 141),
(95987377, 'Organic Brown Rice', 'Organic brown rice, a whole grain with a nutty flavor and rich in fiber. Brown rice is perfect for a healthy, filling meal and works great as a side dish or base for stir-fries and bowls.', 3.50, 'https://www.pexels.com/photo/brown-rice-1421261/', 'FOO005', false, 142),
(95987378, 'Organic Almond Butter', 'Organic almond butter, creamy and rich, perfect for spreading on toast, adding to smoothies, or baking into delicious recipes. Made with just almonds, it is a healthy source of protein and healthy fats.', 5.00, 'https://www.pexels.com/photo/almond-butter-1421261/', 'FOO005', false, 143),
(95987379, 'Organic Peanut Butter', 'Organic peanut butter, creamy and packed with flavor. Great for spreading, adding to smoothies, or using in cooking, this butter is a healthy alternative to regular peanut butter, with no added sugars or preservatives.', 4.50, 'https://www.pexels.com/photo/peanut-butter-1421261/', 'FOO005', false, 144),
(95987380, 'Organic Cashew Butter', 'Organic cashew butter, smooth and rich, made from high-quality organic cashews. Perfect for spreading, baking, or adding to smoothies, this butter provides healthy fats and a creamy texture.', 5.30, 'https://www.pexels.com/photo/cashew-butter-1421261/', 'FOO005', false, 145);
